### PR TITLE
Fix missing c api impls

### PR DESCRIPTION
**Pull request by mathstuf**

### CODE REVIEW

**Comment by cyrush** [comment]
@mathstuf thanks for fixing these!
Would it be possible to add simple tests to make sure they stay fixed?

They would go inside one of these two files:

https://github.com/LLNL/conduit/blob/develop/src/tests/conduit/c/t_c_conduit_node.cpp
https://github.com/LLNL/conduit/blob/develop/src/tests/conduit/c/t_c_conduit_node_set.cpp

**Comment by mathstuf** [comment]
I'm not sure how to use the `data_ptr` and `element_ptr` functions. I found these while testing Catalyst's ABI where we export Conduit's C API and I want to detect when anything changes in an ABI-breaking way.

**Comment by mathstuf** [comment]
Whoops, still a typo here.

**Comment by cyrush** [comment]
looks good, thanks again!

**Pull request merged**
