### PR TITLE
Small CMake changes to better export HDF5

### PR DESCRIPTION
**Pull request by white238**
* Support HDF5's CMake build system which doesn't have the same h5cc as the autoconf system
* Remove duplicate include

### CODE REVIEW

**Comment by cyrush** [comment]
thanks @white238 !

CI pointed out something is a little off with the -l parsing logic:

```
/home/travis/build/LLNL/conduit/uberenv_libs/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-4.8/hdf5-1.8.21-hztuay2cploaj2mqadkfgzzamolwap5p/lib -lhdf5 -L/home/travis/build/LLNL/conduit/uberenv_libs/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-4.8/zlib-1.2.11-fhhwxo52v4wm5y6x64moev63l3zi6t2q/lib  -l-lz -l-ldl -l-lm -L /home/travis/build/LLNL/conduit/uberenv_libs/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-4.8/zfpcmake-0.5.5-hh2pusrgd52xqipm5x5bzl4lxqjc37gn/lib -lzfp -ldl -lrt -pthread -o conduit_example
/usr/bin/ld: cannot find -l-lz
/usr/bin/ld: cannot find -l-ldl
/usr/bin/ld: cannot find -l-lm
```
(from: https://travis-ci.org/LLNL/conduit/jobs/582944436#L2615)


Also, feel free to add yourself to the contributors in the docs:

https://github.com/LLNL/conduit/blob/master/src/docs/sphinx/index.rst

**Comment by white238** [comment]
CMake and its string parsing strikes again! I'll more thoroughly test the regex and push up a fix today.

**Comment by cyrush** [comment]
@white238 resolved conflict with master, can you quickly double check the changes?

**Comment by white238** [comment]
looks good to me!

**Comment by cyrush** [comment]
@white238 thanks!

**Pull request merged**
