### PR TITLE
Example for arbitrary-sized storage of vertex and element fields.

### PR DESCRIPTION
**Pull request by agcapps**
This PR adds an example that shows how to use arbitrary-sized arrays for vertex and element fields in structured mesh data.  This allows the zero-copy use of arrays that store ghost zones with Conduit.

### CODE REVIEW

**Comment by agcapps** [comment]
I guess I could have written "over-sized" instead of "arbitrary-sized," since the arrays storing field data do have lower bounds on their sizes.

**Review by rhornung67 — APPROVED** [review]
Thank you @agcapps

**Comment by cyrush** [comment]
Looks good so far!

I tried to think of a more specific name than `arbitrary` -- how about: `strided_structured`

**Review by cyrush — COMMENTED** [review]
One suggestion: Can we add an ASCII Art diagram to the example?
That context is super helpful for examples like this.

**Review by cyrush — APPROVED** [review]

**Comment by agcapps** [comment]
@cyrush , once I went to the trouble of logging out and logging back in, I was able to merge this PR and delete the branch.

**Comment by cyrush** [comment]
thanks!

**Pull request merged**
