### PR TITLE
Use Data Accessor `set` to clean up generate sides further

### LINKED ISSUE #1243: Refactor Generate Sides code to take advantage of `data_accessor` set
Now that #1143 is complete, we can finish cleaning up generate_sides templating. See #1138 for more info and discussion.

### PR DESCRIPTION
**Pull request by JustinPrivitera**
Resolves #1243

Thanks to #1143, we can clean up `generate_sides` even more.

How does this look @cyrush?

### CODE REVIEW

**Comment by BradWhitlock** [comment]
What's the performance difference? I'm assuming it's slower.

**Comment by JustinPrivitera** [comment]
@BradWhitlock I will do some timings and report back.

**Comment by JustinPrivitera** [comment]
The timings are just about the same. We have a maybe 0.5% speedup with the changes I've made.

I think it's about the same because we were doing a whole lot of static casts before; not much has changed other than the way we do those casts.

**Comment by cyrush** [comment]
thanks @JustinPrivitera  - data accessor is using the same basic strategy as the templating here, its just packaged into a simpler interface that is compiled once.

**Pull request merged**
