### PR TITLE
Blueprint Silo I/O Add root file extension option

### LINKED ISSUE #1191: Silo root file in ParaView
Hello,

When writing to Silo, Conduit generates a root file whose filename ends in `.root`. Using the latest version of ParaView, that file isn't recognized as anything that can be opened and I have to manually allow all file types and manually select the `VisItSiloReader` in order to open it. Is there a way to make the root file end in `.silo` as well?

Thanks!

### PR DESCRIPTION
**Pull request by JustinPrivitera**
Resolves #1191

Also added a test for this. Now you can specify "default", "root", and "silo" as root file extensions. These are ignored if overlink is turned on.

### CODE REVIEW

**Review by cyrush — APPROVED** [review]
Thanks @JustinPrivitera !

**Comment by ibaned** [comment]
@JustinPrivitera it looks like something went wrong in the merge of this PR? the merge commit [c72fb73](https://github.com/LLNL/conduit/commit/c72fb7336a02e2dd45211a44cb4eed465584b535) doesn't seem to actually include most of the changes of the PR, and the functionality isn't present in the current `develop` branch

**Comment by ibaned** [comment]
@cyrush

**Comment by JustinPrivitera** [comment]
I have an idea of what went wrong. I did some messy things with git last week and may have reverted these changes by accident. 😢 I'll get this fixed for you today.

**Comment by JustinPrivitera** [comment]
@ibaned sorry about this. I fixed it here: #1196

**Comment by ibaned** [comment]
No worries at all! I've been bitten by Git many times!

**Pull request merged**
