### PR TITLE
add unstructured geometry utility functions

### PR DESCRIPTION
**Pull request by xjrc**
The changes in this pull request add a number of useful unstructured mesh transformation functions to the Blueprint namespace. These new procedures will be particularly helpful for users that are looking to work with centroid-driven geometries.

The full list of changes that are included in this  pull request are as follows:

- [x] Implement `blueprint::mesh::unstructured::generate_centroids`.
- [x] Implement `blueprint::mesh::unstructured::generate_points`.
- [x] Implement `blueprint::mesh::unstructured::generate_lines`.
- [x] Implement `blueprint::mesh::unstructured::generate_faces`.
- [x] Implement `blueprint::mesh::unstructured::generate_sides`.
  - [x] Add support for 2D geometry types (e.g. tris, quads, polygons).
  - [x] Add support for 3D geometry types (e.g. tets, hexs, polyhedra).
- [x] Implement `blueprint::mesh::unstructured::generate_corners`.
  - [x] Add support for 2D geometry types (e.g. tris, quads, polygons).
  - [x] Add support for 3D geometry types (e.g. tets, hexs, polyhedra).
- [x] Add test cases for `blueprint::mesh::unstructured::generate_centroids`.
- [x] Add test cases for `blueprint::mesh::unstructured::generate_points`.
- [x] Add test cases for `blueprint::mesh::unstructured::generate_lines`.
- [x] Add test cases for `blueprint::mesh::unstructured::generate_faces`.
- [x] Add test cases for `blueprint::mesh::unstructured::generate_sides`.
- [x] Add test cases for `blueprint::mesh::unstructured::generate_corners`.
- [x] Add mapping structures for the `blueprint::mesh::unstructured::generate_*` functions.
- [x] Test the mapping structures for the `blueprint::mesh::unstructured::generate_*` functions.

### CODE REVIEW

**Comment by xjrc** [comment]
@cyrush: I consider this PR to be ready for a preliminary review at this stage, but it's important to note that a few useful capabilities are missing due to limitations in Blueprint. In particular, I've had users interested in this capability express a need for quick and easy bidirectional association between source elements and derivative elements for each of these `generate_*` functions. This is currently a challenge because this association is fundamentally a sparse table, which Blueprint has trouble representing in a space-efficient way.

Despite these limitations, feel free to take a look at what I've got so far and let me know what you think of the new function signatures and infrastructure. Thanks in advance for your help!

**Comment by xjrc** [comment]
@cyrush: I've added the topology mappings to the `blueprint::mesh::unstructured::generate_*` functions as we discussed and wrote some new test/validation code for each of these new outputs. With these additions in place, I believe this pull request to be ready for review. Thanks and please let me know if you have any comments or questions.

**Comment by cyrush** [comment]
@xjrc thanks!

**Comment by xjrc** [comment]
@cyrush: Certainly; I've updated the changelog with my most recent commit. Please let me know if you'd like me to adjust anything else!

**Pull request merged**
