### PR TITLE
Added utility functions helpful in partitioning and reordering topologies.

### PR DESCRIPTION
**Pull request by BradWhitlock**
This PR includes some functions that are useful in partitioning and topology re-ordering.

### CODE REVIEW

**Comment by BradWhitlock** [comment]
Building the docs failed because it can't find the "read the docs" theme. Also, the uberenv build fails locating compilers. I don't think I could have broken these things.

**Comment by cyrush** [comment]
@BradWhitlock -- yes sorry, I healed RTD and the uberenv install test in #1181. Can you merge develop into your branch and we can re-run full CI.

**Comment by BradWhitlock** [comment]
@cyrush - will do.

**Review by cyrush — APPROVED** [review]
Looks good, thanks @BradWhitlock !

**Comment by BradWhitlock** [comment]
Thanks for reviewing.

**Pull request merged**
