### PR TITLE
Feature/il blueprint redecompose

### PR DESCRIPTION
**Pull request by BradWhitlock**
This PR includes support for partitioning meshes in serial and parallel per sections 2.1,2.2,2.3,2.4 of LLNL contract B646485. Blueprint contains partition() functions that will do the repartitioning according to a node containing various options, including selections that identify regions of the mesh to pull out. Partitioning based on element-centered fields is also supported.

### CODE REVIEW

**Comment by BradWhitlock** [comment]
Hey @cyrush, some of the structured merge came in a few days after the PR was started. I fixed the CI build/test failures. They were mainly install issues or Windows glitches (symbol visibility, long/int64). I'll monitor this PR for any feedback you may have.

**Comment by cyrush** [comment]
@BradWhitlock I looked over most everything, looks really good!

I am going to review a bit more next week then plan to merge. 

Post merge I may make a few minor changes --> (change class names from snake_case to CamelCase).  And then I'll start putting it to use to see if I have questions or more feedback.

**Comment by cyrush** [comment]
this is an awesome set of functionality !

**Comment by BradWhitlock** [comment]
Hi @cyrush, just saw your comments. Glad it's looking okay, apart from the CamelCase issue. Sorry about that (I've been in snake case for a while). I'll continue to check in here for your feedback. Let me know if you run into any issues.

**Comment by rhornung67** [comment]
> Hi @cyrush, just saw your comments. Glad it's looking okay, apart from the CamelCase issue. Sorry about that (I've been in snake case for a while). I'll continue to check in here for your feedback. Let me know if you run into any issues.

I think Cyrus calls it 'pothole' case... 😄

**Comment by cyrush** [comment]
`snake_case` is the cooler name these days, and some days I strive to be cool.

**Comment by cyrush** [comment]
thanks @BradWhitlock -- I'll keep you posted.

**Review by cyrush — APPROVED** [review]
Looks good, I made the minor adjustments I mentioned. 
This is ready and I will merge. 
We can follow up with future PRs if we need to adjust more.

**Pull request merged**
