### PR TITLE
Feature/relay io read write offset

### PR DESCRIPTION
**Pull request by kevinhkhuynh**
PR for issue #689 

TODO:

The API needs to be extended to the HDF5Handler and IOHandler class. Currently, the new feature is only implemented for the functions within the conduit_relay_io_hdf5.cpp class. I can get started on this next week.

### CODE REVIEW

**Comment by cyrush** [comment]
@kevinhkhuynh Good job weaving in the options and thank you for the very detailed tests, including error cases -- Really nice work!

As is, I think this is a good chunk of work that we should merge now, and then move on to propgate other changes in the API.:

Before we merge, can you add two things:
- Can you add an entry to the CHANGELOG.md file describing this addition?
- Can you add yourself to the contributors list in the docs?  (https://github.com/LLNL/conduit/blob/develop/src/docs/sphinx/index.rst)


For future work (in addition to the I/O Handle support),  when looking at the tests, one other thing came to mind:

For reading (and possibly for writing as well),  it seems like we may also want to add `size` option to allow us to read/write a subset of a leaf?

**Review by cyrush — APPROVED** [review]
Nice job, thanks!

**Comment by cyrush** [comment]
@kevinhkhuynh thanks for adding the size support

I am  adapting a slab read test that we had before to use the new `stride` and `size` options, b/c that is a quick path to add a new test.

When reading using size, the resulting node seems to be allocated at the full size, here is my example:

```
    // create a simple buffer of doubles
    Node n;
    
    n["full_data"].set(DataType::c_double(20));
    
    double *vin = n["full_data"].value();
    
    for(int i=0;i<20;i++)
    {
        vin[i] = i;
    }
    
    CONDUIT_INFO("Example Full Data")
    
    n.print();

    io::hdf5_write(n,"tout_hdf5_slab_opts.hdf5");
    
    // read 10 entries (as above test, but using hdf5 read options
    
    Node n_res;
    
    Node opts;
    opts["stride"] = 2;
    opts["size"]   = 10;

    Node nload;
    io::hdf5_read("tout_hdf5_slab_opts.hdf5:full_data",opts,nload);
    nload.print();
```

full data:
`[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0]`

read result
`[0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]`

I think we want it to be the size of the `size` option?

**Comment by kevinhkhuynh** [comment]
> 
> 
> @kevinhkhuynh thanks for adding the size support
> 
> I am adapting a slab read test that we had before to use the new `stride` and `size` options, b/c that is a quick path to add a new test.
> 
> When reading using size, the resulting node seems to be allocated at the full size, here is my example:
> 
> ```
>     // create a simple buffer of doubles
>     Node n;
>     
>     n["full_data"].set(DataType::c_double(20));
>     
>     double *vin = n["full_data"].value();
>     
>     for(int i=0;i<20;i++)
>     {
>         vin[i] = i;
>     }
>     
>     CONDUIT_INFO("Example Full Data")
>     
>     n.print();
> 
>     io::hdf5_write(n,"tout_hdf5_slab_opts.hdf5");
>     
>     // read 10 entries (as above test, but using hdf5 read options
>     
>     Node n_res;
>     
>     Node opts;
>     opts["stride"] = 2;
>     opts["size"]   = 10;
> 
>     Node nload;
>     io::hdf5_read("tout_hdf5_slab_opts.hdf5:full_data",opts,nload);
>     nload.print();
> ```
> 
> full data:
> `[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0]`
> 
> read result
> `[0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]`
> 
> I think we want it to be the size of the `size` option?

Ah, I added a fix for that in the second PR a few hours ago. Maybe I'll just copy it and push it here instead.

**Comment by kevinhkhuynh** [comment]
> 
> 
> @kevinhkhuynh thanks for adding the size support
> 
> I am adapting a slab read test that we had before to use the new `stride` and `size` options, b/c that is a quick path to add a new test.
> 
> When reading using size, the resulting node seems to be allocated at the full size, here is my example:
> 
> ```
>     // create a simple buffer of doubles
>     Node n;
>     
>     n["full_data"].set(DataType::c_double(20));
>     
>     double *vin = n["full_data"].value();
>     
>     for(int i=0;i<20;i++)
>     {
>         vin[i] = i;
>     }
>     
>     CONDUIT_INFO("Example Full Data")
>     
>     n.print();
> 
>     io::hdf5_write(n,"tout_hdf5_slab_opts.hdf5");
>     
>     // read 10 entries (as above test, but using hdf5 read options
>     
>     Node n_res;
>     
>     Node opts;
>     opts["stride"] = 2;
>     opts["size"]   = 10;
> 
>     Node nload;
>     io::hdf5_read("tout_hdf5_slab_opts.hdf5:full_data",opts,nload);
>     nload.print();
> ```
> 
> full data:
> `[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0]`
> 
> read result
> `[0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]`
> 
> I think we want it to be the size of the `size` option?

I have pushed the fix. Please let me know if the problem still persists.

**Comment by cyrush** [comment]
looks good thanks!

I pushed my test, and will merge pending CI checks.

**Comment by kevinhkhuynh** [comment]
> 
> 
> looks good thanks!
> 
> I pushed my test, and will merge pending CI checks.

Thanks!

**Comment by cyrush** [comment]
thanks again @kevinhkhuynh !

**Pull request merged**
