### PR TITLE
use custom namespace for rapidjson to avoid sym collision 

### PR DESCRIPTION
**Pull request by cyrush**

### CODE REVIEW

**Comment by cyrush** [comment]
@xjrc  change to fix collision issue.  Is there a way to verify this fix solves the issue you saw?

**Comment by xjrc** [comment]
@cyrush: Yes, I can run some tests this afternoon.

**Comment by cyrush** [comment]
awesome, thanks!

**Review by xjrc — APPROVED** [review]
@cyrush: I tested this out and it works! Thanks for getting to this so quickly.

**Pull request merged**
