### PR TITLE
support YAML schema

### PR DESCRIPTION
**Pull request by JustinPrivitera**
There is a bit more to do but this is a good place to do a merge; this has gotten large enough already.

Follow on work: #1313

### CODE REVIEW

**Comment by cyrush** [comment]
```
 error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17
```
Windows is unhappy b/c of fancy c++ :-)

**Comment by JustinPrivitera** [comment]
> ```
>  error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17
> ```
> 
> Windows is unhappy b/c of fancy c++ :-)

:(

**Comment by JustinPrivitera** [comment]
> Windows is unhappy b/c of fancy c++ :-)

Actually it's my fault; gcc let me get away with something that I shouldn't be allowed to do.

**Review by cyrush — APPROVED** [review]
Looks good!

**Pull request merged**
