### PR TITLE
Catalyst fixes

### PR DESCRIPTION
**Pull request by mathstuf**
---
Various fixes from Catalyst

### CODE REVIEW

**Comment by cyrush** [comment]
@mathstuf  We are planning to do a 0.8.7 release this week.  Happy to get these changes in before the release if that helps with your integration.

**Comment by mathstuf** [comment]
Sure; it'd get rid of 4 commits (well 5 with #1092 included) in our "prep for inclusion into catalyst" branch :) .

**Comment by cyrush** [comment]
@mathstuf ok cool - let me know if you have any more outstanding fixes that you want to tackle in this PR.

**Comment by mathstuf** [comment]
Oh, I see. It's marked as draft :) .

**Comment by cyrush** [comment]
Thanks, merged :-)

**Pull request merged**
